name: Scrape Calendar

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual triggers

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This is important for deployment
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 icalendar pytz
          
      - name: Scrape calendar
        run: python scrape_calendar.py
        
      - name: Upload calendar as artifact
        uses: actions/upload-artifact@v3
        with:
          name: calendar
          path: my_calendar.ics
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
          clean: false  # Don't remove existing files
